package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "calibration_results.csv",
    "hotword.mlir",
    "hotword_timing.mlir",
    "tc_resnet8.pth",
    "tcresnet8-small.pth",
    "tcresnet8small_torch.mlir",
    "test_data-small.npz",
    "test_data.npz",
])
