package(default_visibility = ["//visibility:public"])

exports_files([
    "encoder_mappings.json",
    "feature_cols.pkl",
    "mlp_fraud_model_sigmoid.pt",
    "model_annotated.mlir",
    "scaler.pkl",
    "test_rows.csv",
    "sparkov_fraud_prepped.parquet",
    "sparkov_fraud_encoded.parquet",
])
