load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "path_utils",
    srcs = ["path_utils.py"],
    deps = ["@rules_python//python/runfiles"],
)

py_library(
    name = "export_mlir_utils",
    srcs = ["export_mlir_utils.py"],
)

