"""Generate C++ header containing debug reference data."""

import json
import os


def main():
  workspace_dir = os.environ.get("BUILD_WORKSPACE_DIRECTORY", "")
  if workspace_dir:
    os.chdir(
        os.path.join(
            workspace_dir,
            "demos/cc_fraud",
        )
    )

  input_path = "debug/debug_reference.json"
  output_path = "openfhe/debug_reference.h"

  print(f"Reading {input_path}...")
  with open(input_path, "r") as f:
    data = json.load(f)

  print(f"Generating C++ header {output_path}...")

  hdr_content = []
  hdr_content.append(
      "// Generated by generate_debug_reference_hdr.py. Do not edit."
  )
  hdr_content.append("#ifndef OPENFHE_DEBUG_REFERENCE_H_")
  hdr_content.append("#define OPENFHE_DEBUG_REFERENCE_H_")
  hdr_content.append("")
  hdr_content.append("#include <map>")
  hdr_content.append("#include <string>")
  hdr_content.append("#include <vector>")
  hdr_content.append("")
  hdr_content.append(
      "const std::map<std::string, std::map<std::string, std::vector<float>>>"
      " debug_reference = {"
  )

  for row_key, row_val in data.items():
    hdr_content.append(f'    {{"{row_key}", {{')
    for op_key, op_val in row_val.items():
      val_str = ", ".join(f"{v:.8f}f" for v in op_val)
      hdr_content.append(f'        {{"{op_key}", {{{val_str}}}}},')
    hdr_content.append("    }},")

  hdr_content.append("};")
  hdr_content.append("")
  hdr_content.append("#endif // OPENFHE_DEBUG_REFERENCE_H_")

  with open(output_path, "w") as f:
    f.write("\n".join(hdr_content))
  print("Done!")


if __name__ == "__main__":
  main()
