#ifndef FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_TESTS_ISSUE_36_H_
#define FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_TESTS_ISSUE_36_H_

void sort(int list[10], char L, char R);

#endif  // FULLY_HOMOMORPHIC_ENCRYPTION_TRANSPILER_TESTS_ISSUE_36_H_
