load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "pathutils",
    srcs = ["path_utils.go"],
    importpath = "fully_homomorphic_encryption/demos/common/go/pathutils",
    deps = [
        "@rules_go//go/runfiles",
    ],
)
