name: Build all targets with -c opt
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build-opt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1

      # bazel manages all dependencies hermetically
      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # pin@v3.0.0

      # - name: "Run `bazel build -c opt //...:all`"
      #   run: |
      #     bazel build -c opt //...:all

