name: Build all targets with -c opt
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test:
    runs-on: ubuntu-22.04-8core
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1

      # bazel manages all dependencies hermetically
      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # pin@v3.0.0

      # build demos as separate targets to not overload RAM on the runner
      - name: "Build MNIST demos"
        run: |
          bazel build -c opt //demos/mnist/...:all

      - name: "Build cc_fraud demos"
        run: |
          bazel build -c opt //demos/cc_fraud/...:all

      - name: "Build network_anomaly demos"
        run: |
          bazel build -c opt //demos/network_anomaly/...:all

      # skip hotword and criteo due to RAM limits of CI runner
      # - name: "Build criteo demos"
      #   run: |
      #     bazel build -c opt //demos/criteo/...:all
      # - name: "Build hotword demos"
      #   run: |
      #     bazel build -c opt //demos/hotword/...:all

      - name: "Run MNIST example"
        run: |
          bazel run -c opt //demos/mnist/lattigo:evaluate_fhe

      - name: "Run cc_fraud demos"
        run: |
          bazel run -c opt //demos/cc_fraud/lattigo:evaluate_fhe

      - name: "Run network_anomaly demos"
        run: |
          bazel run -c opt //demos/network_anomaly/lattigo:evaluate_fhe

      # skip hotword and criteo due to RAM limits of CI runner
      # - name: "Build criteo demos"
      #   run: |
      #     bazel run -c opt //demos/criteo/lattigo:evaluate_fhe

